## cadc_task parameters
fly_height: 2.0
min_distance: 0.15
change_dis: 0.5
x:
  vel:
    outputmax: 2.0
    kp: 0.1
    ki: 0.0
    kd: 0.0
    range_rough: 5.0
    range_fine: 0.4
  acc:
    outputmax: 0.5
    kp: 0.5
    ki: 0.0
    kd: 0.0
    range_rough: 0.0
    range_fine: 0.1
y:
  vel:
    outputmax: 2.0
    kp: 0.1
    ki: 0.0
    kd: 0.0
    range_rough: 5.0
    range_fine: 0.4
  acc:
    outputmax: 0.5
    kp: 0.5
    ki: 0.0
    kd: 0.0
    range_rough: 0.0
    range_fine: 0.1
z:
  vel:
    outputmax: 2.0
    kp: 0.1
    ki: 0.0
    kd: 0.0
    range_rough: 5.0
    range_fine: 0.4
  acc:
    outputmax: 0.5
    kp: 0.5
    ki: 0.0
    kd: 0.0
    range_rough: 0.0
    range_fine: 0.1